module.exports = {
    MONGO_CONNECT_URL: process.env.MONGO_CONNECT_URL,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    AWS_S3_BUCKET_PATH: process.env.AWS_S3_BUCKET_PATH
}