export const SET_AUTH_USER="SET_AUTH_USER";
export const SET_PROFILE_IMAGE="SET_PROFILE_IMAGE";
export const GET_FEED="GET_FEED";
export const GET_TIMELINE_FEED="GET_TIMELINE_FEED";
export const SUBMIT_POST="SUBMIT_POST";
export const SET_TIMELINE_USER="SET_TIMELINE_USER";